#!/bin/bash

# PACE Development - Redis Quick Reference

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║            PACE Development - Redis Quick Reference           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "🚀 START & STOP REDIS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Start Redis:"
echo "    🐧 ./scripts/start-redis.sh"
echo "    🪟 scripts\\start-redis.bat"
echo ""
echo "  Stop Redis:"
echo "    🐧 ./scripts/stop-redis.sh"
echo "    🪟 scripts\\stop-redis.bat"
echo ""
echo ""

echo "🗑️  CLEAR CACHE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Clear all Redis cache (with confirmation):"
echo "    🐧 ./scripts/clear-cache.sh"
echo "    🪟 scripts\\clear-cache.bat"
echo ""
echo "  ⚠️  This clears ALL cache:"
echo "     - Bulk job cache (all_jobs)"
echo "     - Query-specific caches"
echo "     - Recommended jobs cache"
echo ""
echo "  Use when:"
echo "     - Testing with fresh data"
echo "     - Jobs should reload from database"
echo "     - Debugging cache issues"
echo ""
echo ""

echo "📊 CHECK REDIS STATUS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  List all keys:"
echo "    docker-compose exec redis redis-cli KEYS '*'"
echo ""
echo "  Count keys:"
echo "    docker-compose exec redis redis-cli DBSIZE"
echo ""
echo "  See specific key:"
echo "    docker-compose exec redis redis-cli GET all_jobs"
echo ""
echo "  Monitor in real-time:"
echo "    docker-compose exec redis redis-cli MONITOR"
echo ""
echo ""

echo "🔍 VIEW LOGS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Redis logs:"
echo "    docker-compose logs -f redis"
echo ""
echo "  Backend logs (shows cache operations):"
echo "    Look for: [CACHE HIT], [CACHE MISS], [CACHE SET]"
echo ""
echo ""

echo "📋 REDIS CONNECTION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Connection string:"
echo "    redis://localhost:6379"
echo ""
echo "  Redis CLI (interactive):"
echo "    docker-compose exec redis redis-cli"
echo ""
echo ""

echo "  For detailed documentation, see: scripts/README.md"
echo ""
