
export const jobData = [
    {
        id: 1,
        title: "Junior Software Developer",
        company: "Accenture Philippines",
        location: "BGC, Taguig",
        salary: 42,
        type: "Full-time",
        postedDate: new Date("2026-02-03"),
        logo: "A",
        experienceLevel: "Entry Level",
        workType: "Hybrid",
    },
    {
        id: 2,
        title: "IT Support Specialist",
        company: "Globe Telecom",
        location: "Makati City",
        salary: 30,
        type: "Full-time",
        postedDate: new Date("2026-02-02"),
        logo: "G",
        experienceLevel: "Entry Level",
        workType: "On-site",
    },
    {
        id: 3,
        title: "Web Developer Intern",
        company: "Freelancer.com",
        location: "Remote",
        salary: 17,
        type: "Internship",
        postedDate: new Date("2026-01-29"),
        logo: "F",
        experienceLevel: "Internship",
        workType: "Remote",
    },
    {
        id: 4,
        title: "Senior Data Analyst",
        company: "BDO Unibank",
        location: "Ortigas, Pasig",
        salary: 65,
        type: "Full-time",
        postedDate: new Date("2026-01-31"),
        logo: "B",
        experienceLevel: "Senior",
        workType: "Hybrid",
    },
    {
        id: 5,
        title: "UI/UX Designer",
        company: "Canva Philippines",
        location: "BGC, Taguig",
        salary: 55,
        type: "Full-time",
        postedDate: new Date("2026-02-04"),
        logo: "C",
        experienceLevel: "Mid-Level",
        workType: "Hybrid",
    },
    {
        id: 6,
        title: "Senior Mobile Developer",
        company: "GCash",
        location: "Makati City",
        salary: 80,
        type: "Full-time",
        postedDate: new Date("2026-02-01"),
        logo: "GC",
        experienceLevel: "Senior",
        workType: "On-site",
    },
    {
        id: 7,
        title: "Technical Writer",
        company: "Shopee Philippines",
        location: "Remote",
        salary: 35,
        type: "Part-time",
        postedDate: new Date("2026-01-22"),
        logo: "S",
        experienceLevel: "Mid-Level",
        workType: "Remote",
    },
    {
        id: 8,
        title: "Lead Cloud Engineer",
        company: "AWS Philippines",
        location: "BGC, Taguig",
        salary: 95,
        type: "Full-time",
        postedDate: new Date("2026-01-30"),
        logo: "AW",
        experienceLevel: "Lead",
        workType: "Hybrid",
    },
    {
        id: 9,
        title: "Frontend Developer",
        company: "Zalora Philippines",
        location: "Makati City",
        salary: 45,
        type: "Full-time",
        postedDate: new Date("2026-02-04"),
        logo: "Z",
        experienceLevel: "Mid-Level",
        workType: "Hybrid",
    },
    {
        id: 10,
        title: "DevOps Engineer",
        company: "Grab Philippines",
        location: "BGC, Taguig",
        salary: 70,
        type: "Full-time",
        postedDate: new Date("2026-02-03"),
        logo: "GR",
        experienceLevel: "Senior",
        workType: "On-site",
    },
    {
        id: 11,
        title: "Product Manager",
        company: "Lazada Philippines",
        location: "Makati City",
        salary: 75,
        type: "Full-time",
        postedDate: new Date("2026-02-02"),
        logo: "L",
        experienceLevel: "Senior",
        workType: "Hybrid",
    },
    {
        id: 12,
        title: "Junior QA Tester",
        company: "Thinking Machines",
        location: "Remote",
        salary: 28,
        type: "Full-time",
        postedDate: new Date("2026-02-05"),
        logo: "TM",
        experienceLevel: "Entry Level",
        workType: "Remote",
    },
    {
        id: 13,
        title: "Business Analyst",
        company: "Ayala Corporation",
        location: "Makati City",
        salary: 50,
        type: "Full-time",
        postedDate: new Date("2026-02-04"),
        logo: "AC",
        experienceLevel: "Mid-Level",
        workType: "On-site",
    },
    {
        id: 14,
        title: "Marketing Intern",
        company: "Foodpanda Philippines",
        location: "BGC, Taguig",
        salary: 15,
        type: "Internship",
        postedDate: new Date("2026-01-28"),
        logo: "FP",
        experienceLevel: "Internship",
        workType: "Hybrid",
    },
    {
        id: 15,
        title: "Cybersecurity Specialist",
        company: "Union Bank",
        location: "Ortigas, Pasig",
        salary: 85,
        type: "Full-time",
        postedDate: new Date("2026-02-01"),
        logo: "UB",
        experienceLevel: "Senior",
        workType: "On-site",
    },
];

export const jobTypes = ["Full-time", "Part-time", "Internship"];
export const experienceLevels = ["Internship", "Entry Level", "Mid-Level", "Senior", "Lead"];
export const workTypes = ["Remote", "Hybrid", "On-site"];
export const dateFilters = [
    { label: "Last 24 hours", value: "24h" },
    { label: "Last Week", value: "week" },
    { label: "Last Month", value: "month" },
    { label: "Anytime", value: "anytime" },
];
export const sortOptions = [
    { label: "Most Relevant", value: "relevant" },
    { label: "Newest First", value: "newest" },
    { label: "Salary: High to Low", value: "salary-desc" },
    { label: "Salary: Low to High", value: "salary-asc" },
];
