"""Add alumni_code to student_records for true 1-to-1 relationship

Revision ID: 03f0c9f0a707
Revises: 6725edba2d19
Create Date: 2026-02-06 13:02:27.001779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03f0c9f0a707'
down_revision: Union[str, Sequence[str], None] = '6725edba2d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_records', sa.Column('alumni_code', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'student_records', ['alumni_code'])
    op.create_foreign_key(None, 'student_records', 'alumni', ['alumni_code'], ['alumni_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_records', type_='foreignkey')
    op.drop_constraint(None, 'student_records', type_='unique')
    op.drop_column('student_records', 'alumni_code')
    # ### end Alembic commands ###
