"""add soft delete fields and transaction logs

Revision ID: 248d2f7dfdb1
Revises: 817dc1b42ad0
Create Date: 2026-02-10 15:09:02.104374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '248d2f7dfdb1'
down_revision: Union[str, Sequence[str], None] = '817dc1b42ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
