"""Removing constraint on student_code in alumni table

Revision ID: 261a24282d17
Revises: 9305858246b8
Create Date: 2026-02-06 12:39:36.791671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '261a24282d17'
down_revision: Union[str, Sequence[str], None] = '9305858246b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni', 'student_code',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni', 'student_code',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
