"""Add unique constraints for college_dept and courses tables

Revision ID: 363c899058c5
Revises: db782a938bb6
Create Date: 2026-02-08 18:51:59.079982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '363c899058c5'
down_revision: Union[str, Sequence[str], None] = 'db782a938bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_college_depts_college_dept_abbv'), 'college_depts', ['college_dept_abbv'], unique=True)
    op.create_index(op.f('ix_college_depts_college_dept_name'), 'college_depts', ['college_dept_name'], unique=True)
    op.create_index(op.f('ix_courses_course_abbv'), 'courses', ['course_abbv'], unique=True)
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_abbv'), table_name='courses')
    op.drop_index(op.f('ix_college_depts_college_dept_name'), table_name='college_depts')
    op.drop_index(op.f('ix_college_depts_college_dept_abbv'), table_name='college_depts')
    # ### end Alembic commands ###
