"""added delete cascade on users, alumni, skills, and student_records

Revision ID: 5d0ec371babd
Revises: 4578e7b60b1e
Create Date: 2026-02-06 20:51:27.583085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d0ec371babd'
down_revision: Union[str, Sequence[str], None] = '4578e7b60b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alumni_student_code_fkey'), 'alumni', type_='foreignkey')
    op.drop_constraint(op.f('alumni_user_code_fkey'), 'alumni', type_='foreignkey')
    op.create_foreign_key(None, 'alumni', 'student_records', ['student_code'], ['student_code'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alumni', 'users', ['user_code'], ['user_code'], ondelete='CASCADE')
    op.drop_constraint(op.f('skills_alumni_code_fkey'), 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'alumni', ['alumni_code'], ['alumni_code'], ondelete='CASCADE')
    op.drop_constraint(op.f('skills_list_skill_code_fkey'), 'skills_list', type_='foreignkey')
    op.create_foreign_key(None, 'skills_list', 'skills', ['skill_code'], ['skill_code'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_records_alumni_code_fkey'), 'student_records', type_='foreignkey')
    op.drop_constraint(op.f('student_records_degree_code_fkey'), 'student_records', type_='foreignkey')
    op.create_foreign_key(None, 'student_records', 'alumni', ['alumni_code'], ['alumni_code'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_records', 'degrees', ['degree_code'], ['degree_code'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_records', type_='foreignkey')
    op.drop_constraint(None, 'student_records', type_='foreignkey')
    op.create_foreign_key(op.f('student_records_degree_code_fkey'), 'student_records', 'degrees', ['degree_code'], ['degree_code'])
    op.create_foreign_key(op.f('student_records_alumni_code_fkey'), 'student_records', 'alumni', ['alumni_code'], ['alumni_code'])
    op.drop_constraint(None, 'skills_list', type_='foreignkey')
    op.create_foreign_key(op.f('skills_list_skill_code_fkey'), 'skills_list', 'skills', ['skill_code'], ['skill_code'])
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(op.f('skills_alumni_code_fkey'), 'skills', 'alumni', ['alumni_code'], ['alumni_code'])
    op.drop_constraint(None, 'alumni', type_='foreignkey')
    op.drop_constraint(None, 'alumni', type_='foreignkey')
    op.create_foreign_key(op.f('alumni_user_code_fkey'), 'alumni', 'users', ['user_code'], ['user_code'])
    op.create_foreign_key(op.f('alumni_student_code_fkey'), 'alumni', 'student_records', ['student_code'], ['student_code'])
    # ### end Alembic commands ###
