"""Made sure alumni only has 1 student record

Revision ID: 6725edba2d19
Revises: 261a24282d17
Create Date: 2026-02-06 12:57:26.867734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6725edba2d19'
down_revision: Union[str, Sequence[str], None] = '261a24282d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alumni', ['student_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alumni', type_='unique')
    # ### end Alembic commands ###
