"""add soft delete fields and transaction logs

Revision ID: 817dc1b42ad0
Revises: f91e568c6bb2
Create Date: 2026-02-10 15:05:07.453484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '817dc1b42ad0'
down_revision: Union[str, Sequence[str], None] = 'f91e568c6bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('alumni', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('alumni_user_code_fkey'), 'alumni', type_='foreignkey')
    op.drop_constraint(op.f('alumni_student_code_fkey'), 'alumni', type_='foreignkey')
    op.create_foreign_key(None, 'alumni', 'student_records', ['student_code'], ['student_code'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alumni', 'users', ['user_code'], ['user_code'], ondelete='SET NULL')
    op.add_column('college_depts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('college_depts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('courses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('courses', 'college_dept_code',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('courses_college_dept_code_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'college_depts', ['college_dept_code'], ['college_dept_code'], ondelete='SET NULL')
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('skills', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('skills', 'alumni_code',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('skills_alumni_code_fkey'), 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'alumni', ['alumni_code'], ['alumni_code'], ondelete='SET NULL')
    op.add_column('student_records', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('student_records', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('student_records', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('student_records', 'course_code',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_records', 'alumni_code',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('student_records_alumni_code_fkey'), 'student_records', type_='foreignkey')
    op.drop_constraint(op.f('student_records_course_code_fkey'), 'student_records', type_='foreignkey')
    op.create_foreign_key(None, 'student_records', 'alumni', ['alumni_code'], ['alumni_code'], ondelete='SET NULL')
    op.create_foreign_key(None, 'student_records', 'courses', ['course_code'], ['course_code'], ondelete='SET NULL')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'student_records', type_='foreignkey')
    op.drop_constraint(None, 'student_records', type_='foreignkey')
    op.create_foreign_key(op.f('student_records_course_code_fkey'), 'student_records', 'courses', ['course_code'], ['course_code'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_records_alumni_code_fkey'), 'student_records', 'alumni', ['alumni_code'], ['alumni_code'], ondelete='CASCADE')
    op.alter_column('student_records', 'alumni_code',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('student_records', 'course_code',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('student_records', 'deleted_at')
    op.drop_column('student_records', 'is_deleted')
    op.drop_column('student_records', 'updated_at')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(op.f('skills_alumni_code_fkey'), 'skills', 'alumni', ['alumni_code'], ['alumni_code'], ondelete='CASCADE')
    op.alter_column('skills', 'alumni_code',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('skills', 'deleted_at')
    op.drop_column('skills', 'is_deleted')
    op.drop_column('skills', 'updated_at')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_college_dept_code_fkey'), 'courses', 'college_depts', ['college_dept_code'], ['college_dept_code'], ondelete='CASCADE')
    op.alter_column('courses', 'college_dept_code',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('courses', 'deleted_at')
    op.drop_column('courses', 'is_deleted')
    op.drop_column('college_depts', 'deleted_at')
    op.drop_column('college_depts', 'is_deleted')
    op.drop_constraint(None, 'alumni', type_='foreignkey')
    op.drop_constraint(None, 'alumni', type_='foreignkey')
    op.create_foreign_key(op.f('alumni_student_code_fkey'), 'alumni', 'student_records', ['student_code'], ['student_code'], ondelete='CASCADE')
    op.create_foreign_key(op.f('alumni_user_code_fkey'), 'alumni', 'users', ['user_code'], ['user_code'], ondelete='CASCADE')
    op.drop_column('alumni', 'deleted_at')
    op.drop_column('alumni', 'is_deleted')
    # ### end Alembic commands ###
