"""Initial Schema

Revision ID: 8c52abfdcb16
Revises: 3d0bbfd247be
Create Date: 2026-02-03 23:47:02.846432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


#


# revision identifiers, used by Alembic.
revision: str = '8c52abfdcb16'
down_revision: Union[str, Sequence[str], None] = '3d0bbfd247be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degrees',
    sa.Column('degree_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('degree_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('degree_code', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('degree_code')
    )
    op.create_index(op.f('ix_degrees_degree_id'), 'degrees', ['degree_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_code', sa.Uuid(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_code')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('student_records',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('year_graduated', sa.Integer(), nullable=False),
    sa.Column('gwa', sa.Float(), nullable=False),
    sa.Column('avg_prof_grade', sa.Float(), nullable=True),
    sa.Column('avg_elec_grade', sa.Float(), nullable=True),
    sa.Column('ojt_grade', sa.Float(), nullable=True),
    sa.Column('leadership_pos', sa.Boolean(), nullable=True),
    sa.Column('act_member_pos', sa.Boolean(), nullable=True),
    sa.Column('student_code', sa.Uuid(), nullable=False),
    sa.Column('degree_code', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['degree_code'], ['degrees.degree_code'], ),
    sa.PrimaryKeyConstraint('student_code')
    )
    op.create_index(op.f('ix_student_records_student_id'), 'student_records', ['student_id'], unique=True)
    op.create_table('alumni',
    sa.Column('alumni_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=False),
    sa.Column('user_code', sa.Uuid(), nullable=True),
    sa.Column('student_code', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_code'], ['student_records.student_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('alumni_code')
    )
    op.create_index(op.f('ix_alumni_alumni_id'), 'alumni', ['alumni_id'], unique=True)
    op.create_table('skills',
    sa.Column('skill_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('soft_skills_avg', sa.Float(), nullable=True),
    sa.Column('hard_skills_avg', sa.Float(), nullable=True),
    sa.Column('skill_code', sa.Uuid(), nullable=False),
    sa.Column('alumni_code', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_code'], ['alumni.alumni_code'], ),
    sa.PrimaryKeyConstraint('skill_code')
    )
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=True)
    op.create_table('skills_list',
    sa.Column('skill_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('skill_value', sa.Float(), nullable=True),
    sa.Column('sl_code', sa.Uuid(), nullable=False),
    sa.Column('skill_code', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.skill_code'], ),
    sa.PrimaryKeyConstraint('sl_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills_list')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_alumni_alumni_id'), table_name='alumni')
    op.drop_table('alumni')
    op.drop_index(op.f('ix_student_records_student_id'), table_name='student_records')
    op.drop_table('student_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_degrees_degree_id'), table_name='degrees')
    op.drop_table('degrees')
    # ### end Alembic commands ###
