"""Add raw_salary and relax enums for JobListing

Revision ID: 90bd8c2581f4
Revises: 5d0ec371babd
Create Date: 2026-02-06 23:45:49.087402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90bd8c2581f4'
down_revision: Union[str, Sequence[str], None] = '5d0ec371babd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('raw_salary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('job_listings', 'job_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'INTERNSHIP', name='jobtype'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('job_listings', 'work_type',
               existing_type=postgresql.ENUM('REMOTE', 'HYBRID', 'ON_SITE', name='worktype'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('job_listings', 'experience_level',
               existing_type=postgresql.ENUM('INTERNSHIP', 'ENTRY_LEVEL', 'MID_LEVEL', 'SENIOR', 'LEAD', name='experiencelevel'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_listings', 'experience_level',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('INTERNSHIP', 'ENTRY_LEVEL', 'MID_LEVEL', 'SENIOR', 'LEAD', name='experiencelevel'),
               nullable=False)
    op.alter_column('job_listings', 'work_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('REMOTE', 'HYBRID', 'ON_SITE', name='worktype'),
               nullable=False)
    op.alter_column('job_listings', 'job_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'INTERNSHIP', name='jobtype'),
               nullable=False)
    op.drop_column('job_listings', 'raw_salary')
    # ### end Alembic commands ###
