"""Make alumni_code NOT NULL in student_records

Revision ID: a8315ef2730f
Revises: 03f0c9f0a707
Create Date: 2026-02-06 13:08:48.247563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8315ef2730f'
down_revision: Union[str, Sequence[str], None] = '03f0c9f0a707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_records', 'alumni_code',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_records', 'alumni_code',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
