"""added events model

Revision ID: b7399878250c
Revises: ce6a8ff9b493
Create Date: 2026-02-12 23:08:07.485674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7399878250c'
down_revision: Union[str, Sequence[str], None] = 'ce6a8ff9b493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('event_type', sa.Enum('CAREER_FAIR', 'WORKSHOP', 'SEMINAR', 'NETWORKING', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.Uuid(), nullable=False),
    sa.Column('attendees', sa.Integer(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_code')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_table('event_registrations',
    sa.Column('registration_code', sa.Uuid(), nullable=False),
    sa.Column('event_code', sa.Uuid(), nullable=False),
    sa.Column('user_code', sa.Uuid(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_code'], ['events.event_code'], ),
    sa.ForeignKeyConstraint(['user_code'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('registration_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
