"""refactor degrees into courses and added college_dept table

Revision ID: b92ba1e66e67
Revises: 90bd8c2581f4
Create Date: 2026-02-08 18:33:08.211825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b92ba1e66e67'
down_revision: Union[str, Sequence[str], None] = '90bd8c2581f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create new tables first
    op.create_table('college_depts',
    sa.Column('college_dept_id', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('college_dept_abbv', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('college_dept_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('college_dept_desc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('college_dept_code', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('college_dept_code')
    )
    op.create_index(op.f('ix_college_depts_college_dept_id'), 'college_depts', ['college_dept_id'], unique=True)
    op.create_table('courses',
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('course_abbv', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('course_desc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('course_code', sa.Uuid(), nullable=False),
    sa.Column('college_dept_code', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_dept_code'], ['college_depts.college_dept_code'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=True)
    
    # Step 2: Modify student_records - drop old FK constraint FIRST
    op.drop_constraint('student_records_degree_code_fkey', 'student_records', type_='foreignkey')
    
    # Step 3: Now safe to drop degrees table
    op.drop_index(op.f('ix_degrees_degree_id'), table_name='degrees')
    op.drop_table('degrees')
    
    # Step 4: Add new column and create new FK constraint
    op.add_column('student_records', sa.Column('course_code', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'student_records', 'courses', ['course_code'], ['course_code'], ondelete='CASCADE')
    
    # Step 5: Drop old column (after FK is removed)
    op.drop_column('student_records', 'degree_code')
    
    # Step 6: Make course_code NOT NULL (after data migration if needed)
    # Note: You may need to populate course_code before this step in production
    op.alter_column('student_records', 'course_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_records', sa.Column('degree_code', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_records', type_='foreignkey')
    op.create_foreign_key(op.f('student_records_degree_code_fkey'), 'student_records', 'degrees', ['degree_code'], ['degree_code'], ondelete='CASCADE')
    op.drop_column('student_records', 'course_code')
    op.create_table('degrees',
    sa.Column('degree_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('degree_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('degree_code', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('degree_code', name=op.f('degrees_pkey'))
    )
    op.create_index(op.f('ix_degrees_degree_id'), 'degrees', ['degree_id'], unique=True)
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_college_depts_college_dept_id'), table_name='college_depts')
    op.drop_table('college_depts')
    # ### end Alembic commands ###
