"""added transaction logs table

Revision ID: ce6a8ff9b493
Revises: 248d2f7dfdb1
Create Date: 2026-02-10 15:15:27.137663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce6a8ff9b493'
down_revision: Union[str, Sequence[str], None] = '248d2f7dfdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_logs',
    sa.Column('tl_code', sa.Uuid(), nullable=False),
    sa.Column('tl_id', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('tl_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('tl_date', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('tl_code')
    )
    op.create_index(op.f('ix_transaction_logs_tl_id'), 'transaction_logs', ['tl_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_tl_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    # ### end Alembic commands ###
