"""Creating Composite Endpoint for continous creation of User-Student-Alumni records

Revision ID: f005e24dc34a
Revises: 8c52abfdcb16
Create Date: 2026-02-04 00:11:11.798039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f005e24dc34a'
down_revision: Union[str, Sequence[str], None] = '8c52abfdcb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
