"""add cascade delete to courses fk

Revision ID: f91e568c6bb2
Revises: 363c899058c5
Create Date: 2026-02-08 19:07:13.612734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f91e568c6bb2'
down_revision: Union[str, Sequence[str], None] = '363c899058c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_college_dept_code_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'college_depts', ['college_dept_code'], ['college_dept_code'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_college_dept_code_fkey'), 'courses', 'college_depts', ['college_dept_code'], ['college_dept_code'])
    # ### end Alembic commands ###
