from enum import Enum
from pydantic import BaseModel, Field, field_serializer
from typing import Optional, Any
from datetime import datetime
from utils.timezone import get_current_time_gmt8

# Response codes for API endpoints

class ErrorCode(str, Enum):
    """Error codes for API responses"""
    # Duplicate/Conflict errors
    DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
    DUPLICATE_USERNAME = "DUPLICATE_USERNAME"
    DUPLICATE_STUDENT_ID = "DUPLICATE_STUDENT_ID"
    DUPLICATE_ALUMNI_ID = "DUPLICATE_ALUMNI_ID"
    DUPLICATE_DEGREE_ID = "DUPLICATE_DEGREE_ID"  # Legacy - use DUPLICATE_COURSE_ID
    DUPLICATE_COURSE_ID = "DUPLICATE_COURSE_ID"
    DUPLICATE_COURSE_ABBV = "DUPLICATE_COURSE_ABBV"
    DUPLICATE_COURSE_NAME = "DUPLICATE_COURSE_NAME"
    DUPLICATE_COLLEGE_DEPT_ID = "DUPLICATE_COLLEGE_DEPT_ID"
    DUPLICATE_COLLEGE_DEPT_ABBV = "DUPLICATE_COLLEGE_DEPT_ABBV"
    DUPLICATE_COLLEGE_DEPT_NAME = "DUPLICATE_COLLEGE_DEPT_NAME"
    ALUMNI_ALREADY_HAS_STUDENT_RECORD = "ALUMNI_ALREADY_HAS_STUDENT_RECORD"
    
    # Not found errors
    DEGREE_NOT_FOUND = "DEGREE_NOT_FOUND"  # Legacy - use COURSE_NOT_FOUND
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
    COLLEGE_DEPT_NOT_FOUND = "COLLEGE_DEPT_NOT_FOUND"
    ALUMNI_NOT_FOUND = "ALUMNI_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    STUDENT_RECORD_NOT_FOUND = "STUDENT_RECORD_NOT_FOUND"
    
    # Authentication/Authorization errors
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    MISSING_CURRENT_PASSWORD = "MISSING_CURRENT_PASSWORD"
    
    # Validation errors
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    INVALID_YEAR_GRADUATED = "INVALID_YEAR_GRADUATED"
    INVALID_AGE = "INVALID_AGE"
    
    # Generic errors
    REGISTRATION_FAILED = "REGISTRATION_FAILED"


class SuccessCode(str, Enum):
    """Success codes for API responses"""
    # User operations
    USER_CREATED = "USER_CREATED"
    USER_RETRIEVED = "USER_RETRIEVED"
    USERS_RETRIEVED = "USERS_RETRIEVED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USERS_BULK_CREATED = "USERS_BULK_CREATED"
    USERS_BULK_UPDATED = "USERS_BULK_UPDATED"
    USERS_BULK_DELETED = "USERS_BULK_DELETED"
    
    # Alumni operations
    ALUMNI_CREATED = "ALUMNI_CREATED"
    ALUMNI_RETRIEVED = "ALUMNI_RETRIEVED"
    ALUMNI_LIST_RETRIEVED = "ALUMNI_LIST_RETRIEVED"
    ALUMNI_UPDATED = "ALUMNI_UPDATED"
    ALUMNI_DELETED = "ALUMNI_DELETED"
    ALUMNI_BULK_REGISTERED = "ALUMNI_BULK_REGISTERED"
    ALUMNI_BULK_UPDATED = "ALUMNI_BULK_UPDATED"
    ALUMNI_BULK_DELETED = "ALUMNI_BULK_DELETED"
    
    # Student record operations
    STUDENT_RECORD_CREATED = "STUDENT_RECORD_CREATED"
    STUDENT_RECORD_RETRIEVED = "STUDENT_RECORD_RETRIEVED"
    STUDENT_RECORDS_RETRIEVED = "STUDENT_RECORDS_RETRIEVED"
    STUDENT_RECORD_UPDATED = "STUDENT_RECORD_UPDATED"
    STUDENT_RECORD_DELETED = "STUDENT_RECORD_DELETED"
    
    # Degree operations (Legacy - use Course operations)
    DEGREE_CREATED = "DEGREE_CREATED"
    DEGREE_RETRIEVED = "DEGREE_RETRIEVED"
    DEGREES_RETRIEVED = "DEGREES_RETRIEVED"
    DEGREE_UPDATED = "DEGREE_UPDATED"
    DEGREE_DELETED = "DEGREE_DELETED"
    
    # College Department operations
    COLLEGE_DEPT_CREATED = "COLLEGE_DEPT_CREATED"
    COLLEGE_DEPT_RETRIEVED = "COLLEGE_DEPT_RETRIEVED"
    COLLEGE_DEPTS_RETRIEVED = "COLLEGE_DEPTS_RETRIEVED"
    COLLEGE_DEPT_UPDATED = "COLLEGE_DEPT_UPDATED"
    COLLEGE_DEPT_DELETED = "COLLEGE_DEPT_DELETED"
    COLLEGE_DEPTS_BULK_CREATED = "COLLEGE_DEPTS_BULK_CREATED"
    COLLEGE_DEPTS_BULK_UPDATED = "COLLEGE_DEPTS_BULK_UPDATED"
    COLLEGE_DEPTS_BULK_DELETED = "COLLEGE_DEPTS_BULK_DELETED"
    
    # Course operations
    COURSE_CREATED = "COURSE_CREATED"
    COURSE_RETRIEVED = "COURSE_RETRIEVED"
    COURSES_RETRIEVED = "COURSES_RETRIEVED"
    COURSE_UPDATED = "COURSE_UPDATED"
    COURSE_DELETED = "COURSE_DELETED"
    COURSES_BULK_CREATED = "COURSES_BULK_CREATED"
    COURSES_BULK_UPDATED = "COURSES_BULK_UPDATED"
    COURSES_BULK_DELETED = "COURSES_BULK_DELETED"
    
    # Authentication
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
    TOKEN_VALIDATED = "TOKEN_VALIDATED"


class StandardResponse(BaseModel):
    """Standardized response wrapper for all API endpoints"""
    success: bool = Field(..., description="Whether the operation was successful")
    code: str = Field(..., description="Response code (ErrorCode or SuccessCode)")
    message: str = Field(..., description="Human-readable message")
    data: Optional[Any] = Field(default=None, description="Response data (optional)")
    timestamp: datetime = Field(default_factory=get_current_time_gmt8, description="Response timestamp in GMT+8")
    
    @field_serializer('timestamp')
    def serialize_timestamp(self, value: datetime) -> str:
        """Serialize timestamp as YYYY-MM-DD HH:MM:SS"""
        return value.strftime('%Y-%m-%d %H:%M:%S')


class ErrorResponse(BaseModel):
    """Standardized error response"""
    code: ErrorCode
    message: str
